// Generated by ovo. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/tools/get_weather.ts";

export const moduleMap = Object.freeze({
  nodes: Object.freeze({
    __root__: Object.freeze({
      modules: Object.freeze({
        "agent.ts": module_0,
        "tools/get_weather.ts": module_1,
      }),
    }),
  }),
});

export default moduleMap;
